name: Term Feedback
description: Provide feedback on a specific term (class or field) in the schema. This could be to rename the field or change any of its properties.
title: "[Term]: "
labels: ["open-review", "feedback", "openDS term"]
body:
  - type: input
    id: term-name
    attributes:
      label: Term Name
      description: Which terms do you wan to provide feedback on?
      placeholder: "ods:physicalSpecimenID"
    validations:
      required: true
  - type: input
    id: digital-object-name
    attributes:
      label: Digital Object Name
      description: To which Digital Object does the term belong?
      placeholder: "DigitalSpecimen"
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: What is it that you would like to change about the term?
      placeholder: "I would like to rename the term to 'ods:specimenID'"
    validations:
      required: true
